swagger: '2.0'

info:
  version: '0.0.1-SNAPSHOT'
  title: 'API - Animals'
  description: 'API de recursos de manipulação para Animals'

host: localhost:8080
basePath: /api/v1

schemes:
  - http
  - https

produces:
  - "application/json"

paths:

  /animals:
    get:
      summary: Lista todos os animais cadastrados
      description: Lista todos os detalhes dos animais cadastrados.
      operationId: list
      produces:
        - application/json
      responses:
        200:
          description: Representação dos dados de todos os animais cadastrados.
          schema:
            $ref: '#/definitions/ResponseGetAnimals'
        204:
          description: Nenhum animal encontrado
        500:
          description: Erro interno

  /animals/{id}:
    get:
      summary: Lista um animal específico
      description: Lista os detalhes de um animal específico de acordo com o ID.
      operationId: detail
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          type: integer
          required: true
      responses:
        200:
          description: Detalhe do animal encontrado
          schema:
            $ref: '#/definitions/ResponseGetAnimalsById'
        404:
          description: Nenhum animal encontrado correspondente ao ID informado
        500:
          description: Erro interno

definitions:

  ResponseGetAnimals:
    type: object
    properties:
      animais:
        type: array
        items:
          $ref: '#/definitions/Animal'

  ResponseGetAnimalsById:
    type: object
    properties:
      animal:
        $ref: '#/definitions/Animal'

  Animal:
    type: object
    required:
      - name
      - dob
      - ageInDays
      - ageInMonths
      - ageInYears
      - species
    properties:
      name:
        type: string
      dob:
        description: Data de nascimento
        type: string
      ageInDays:
        description: Idade em dias
        type: integer
        format: int64
        minimum: 1
        maximum: 36135
      ageInMonths:
        description: Idade em meses
        type: integer
        format: int64
        minimum: 0
        maximum: 1188
      ageInYears:
        description: Idade em anos
        type: integer
        format: int64
        minimum: 0
        maximum: 99
      species:
        type: string
        enum:
          - FELINE
          - CANINE
